# Generated by Django 2.2.4 on 2019-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('site', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('banner', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=25)),
                ('ram', models.CharField(max_length=25)),
                ('cpu', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('storage', models.CharField(max_length=25)),
            ],
        ),
    ]
