# Generated by Django 2.2.4 on 2019-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='length',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='screen',
            name='inches',
            field=models.CharField(max_length=10),
        ),
    ]
